x86 config

diff --git a/init/nginx-release b/init/nginx-release
--- a/init/nginx-release
+++ b/init/nginx-release
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:          nginx
-# Required-Start:    $local_fs $remote_fs $network $syslog
-# Required-Stop:     $local_fs $remote_fs $network $syslog
+# Provides:	  nginx
+# Required-Start:    $local_fs $remote_fs $network $syslog $named
+# Required-Stop:     $local_fs $remote_fs $network $syslog $named
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: starts the nginx web server
@@ -14,97 +14,185 @@ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/sbin/nginx-release
 NAME=nginx-release
 DESC=nginx-release
-DAEMON_OPTS="-c /usr/local/nginx/conf/nginx-release.conf"
-USER=root
+DAEMON_OPTS="-c /etc/nginx/nginx-release.conf"
 
 # Include nginx defaults if available
-if [ -f /etc/default/nginx ]; then
+if [ -r /etc/default/nginx ]; then
 	. /etc/default/nginx
 fi
 
+STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"
+
 test -x $DAEMON || exit 0
 
-set -e
-
+. /lib/init/vars.sh
 . /lib/lsb/init-functions
 
-test_nginx_config() {
-	if $DAEMON -t $DAEMON_OPTS >/dev/null 2>&1; then
-		return 0
+# Try to extract nginx pidfile
+PID=$(cat /etc/nginx/nginx-release.conf | grep -Ev '^\s*#' | awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") print $2 }' | head -n1)
+if [ -z "$PID" ]; then
+	PID=/run/nginx-release.pid
+fi
+
+if [ -n "$ULIMIT" ]; then
+	# Set ulimit if it is set in /etc/default/nginx
+	ulimit $ULIMIT
+fi
+
+start_nginx() {
+	# Start the daemon/service
+	#
+	# Returns:
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
+		$DAEMON_OPTS 2>/dev/null \
+		|| return 2
+}
+
+test_config() {
+	# Test the nginx configuration
+	$DAEMON -t $DAEMON_OPTS >/dev/null 2>&1
+}
+
+stop_nginx() {
+	# Stops the daemon/service
+	#
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	echo start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
+	start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
+	RETVAL="$?"
+	sleep 1
+	return "$RETVAL"
+}
+
+reload_nginx() {
+	# Function that sends a SIGHUP to the daemon/service
+	start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
+	return 0
+}
+
+rotate_logs() {
+	# Rotate log files
+	start-stop-daemon --stop --signal USR1 --quiet --pidfile $PID --name $NAME
+	return 0
+}
+
+upgrade_nginx() {
+	# Online upgrade nginx executable
+	# http://nginx.org/en/docs/control.html
+	#
+	# Return
+	#   0 if nginx has been successfully upgraded
+	#   1 if nginx is not running
+	#   2 if the pid files were not created on time
+	#   3 if the old master could not be killed
+	if start-stop-daemon --stop --signal USR2 --quiet --pidfile $PID --name $NAME; then
+		# Wait for both old and new master to write their pid file
+		while [ ! -s "${PID}.oldbin" ] || [ ! -s "${PID}" ]; do
+			cnt=`expr $cnt + 1`
+			if [ $cnt -gt 10 ]; then
+				return 2
+			fi
+			sleep 1
+		done
+		# Everything is ready, gracefully stop the old master
+		if start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PID}.oldbin" --name $NAME; then
+			return 0
+		else
+			return 3
+		fi
 	else
-		$DAEMON -t $DAEMON_OPTS
-		return $?
+		return 1
 	fi
 }
 
 case "$1" in
 	start)
-		echo -n "Starting $DESC: "
-		test_nginx_config
-		# Check if the ULIMIT is set in /etc/default/nginx
-		if [ -n "$ULIMIT" ]; then
-			# Set the ulimits
-			ulimit $ULIMIT
-		fi
-		#start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
-		sudo -r $USER start-stop-daemon --start --quiet \
-		    --exec $DAEMON -- $DAEMON_OPTS || true
-		echo "$NAME."
+		log_daemon_msg "Starting $DESC" "$NAME"
+		start_nginx
+		case "$?" in
+			0|1) log_end_msg 0 ;;
+			2)   log_end_msg 1 ;;
+		esac
 		;;
-
 	stop)
-		echo -n "Stopping $DESC: "
-		#start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
-		sudo -r $USER start-stop-daemon --stop --quiet \
-		    --exec $DAEMON || true
-		echo "$NAME."
+		log_daemon_msg "Stopping $DESC" "$NAME"
+		stop_nginx
+		case "$?" in
+			0|1) log_end_msg 0 ;;
+			2)   log_end_msg 1 ;;
+		esac
 		;;
+	restart)
+		log_daemon_msg "Restarting $DESC" "$NAME"
 
-	restart|force-reload)
-		echo -n "Restarting $DESC: "
-		#start-stop-daemon --stop --quiet --pidfile \
-		#    /var/run/$NAME.pid 
-		sudo -r $USER start-stop-daemon --stop --quiet \
-			--exec $DAEMON || true
-		sleep 1
-		test_nginx_config
-		# Check if the ULIMIT is set in /etc/default/nginx
-		if [ -n "$ULIMIT" ]; then
-			# Set the ulimits
-			ulimit $ULIMIT
-		fi
-		#start-stop-daemon --start --quiet --pidfile \
-		#    /var/run/$NAME.pid 
-		sudo -r $USER start-stop-daemon --start --quiet \
-			--exec $DAEMON -- $DAEMON_OPTS || true
-		echo "$NAME."
-		;;
-
-	reload)
-		echo -n "Reloading $DESC configuration: "
-		test_nginx_config
-		#start-stop-daemon --stop --signal HUP --quiet --pidfile /var/run/$NAME.pid \
-		sudo -r $USER start-stop-daemon --stop --signal HUP --quiet \
-		    --exec $DAEMON || true
-		echo "$NAME."
-		;;
-
-	configtest|testconfig)
-		echo -n "Testing $DESC configuration: "
-		if test_nginx_config; then
-			echo "$NAME."
-		else
+		# Check configuration before stopping nginx
+		if ! test_config; then
+			log_end_msg 1 # Configuration error
 			exit $?
 		fi
-		;;
 
+		stop_nginx
+		case "$?" in
+			0|1)
+				start_nginx
+				case "$?" in
+					0) log_end_msg 0 ;;
+					1) log_end_msg 1 ;; # Old process is still running
+					*) log_end_msg 1 ;; # Failed to start
+				esac
+				;;
+			*)
+				# Failed to stop
+				log_end_msg 1
+				;;
+		esac
+		;;
+	reload|force-reload)
+		log_daemon_msg "Reloading $DESC configuration" "$NAME"
+
+		# Check configuration before stopping nginx
+		#
+		# This is not entirely correct since the on-disk nginx binary
+		# may differ from the in-memory one, but that's not common.
+		# We prefer to check the configuration and return an error
+		# to the administrator.
+		if ! test_config; then
+			log_end_msg 1 # Configuration error
+			exit $?
+		fi
+
+		reload_nginx
+		log_end_msg $?
+		;;
+	configtest|testconfig)
+		log_daemon_msg "Testing $DESC configuration"
+		test_config
+		log_end_msg $?
+		;;
 	status)
-		status_of_proc -p /var/run/$NAME.pid "$DAEMON" nginx && exit 0 || exit $?
+		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
+		;;
+	upgrade)
+		log_daemon_msg "Upgrading binary" "$NAME"
+		upgrade_nginx
+		log_end_msg $?
+		;;
+	rotate)
+		log_daemon_msg "Re-opening $DESC log files" "$NAME"
+		rotate_logs
+		log_end_msg $?
 		;;
 	*)
-		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest}" >&2
-		exit 1
+		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest|rotate|upgrade}" >&2
+		exit 3
 		;;
 esac
-
-exit 0
